travis:
  secure:
    BINSTAR_TOKEN: iiz1Tv0DIxlAeX3oFf2zOqnQk4jrKP+e0B/kTTej3PwAzdnhLlOc+k4FTtRF5GYOCTjgTS3pI5q9/8OJKLLL6U70qvzLWFC0WTGVbONb+kw2IeLcY4uMoSTDECLlamofBsznehkQEOY1a/nWsHDPCiNWFjdfVu4YIxuA41lRhpaVQ31nX30f9kLwVLUI9B/11HBwClx3s9P8GZRtidJLvwhqHzSujptdAXZ2C+N3msj6YJugc5TBN23UJkQye5xUhE6W4RkgVzVZhyQg7r3WoJOo8uk+JzUDQLp4P997EkAaY1s7+iv6PVKD1AHsDKt9acAI+LW+20Cv5VAmvKEdrTmTDRYwfDd64e+k6qSWa94+hP8uiZODyOpqcXHD9HLDAECaAPOpEyJhylKIAgllwBPbxib8PZ3NtVS1Tak2n6yH2r0mpgt9vYwVVj28M9U+EsgLrKoODQZ0YKaGHDRiWx1eV4Kqyyvu+cY/9v37Xp+ndD4PmI8SXBj7Nyu1tPHNB7ia4O8RzEHbDG7Jdlt9joaTO2b7XlnJcIxSsSS6h82i/FkYi1ZXR93VL9auxI9qPMKqCf1fEyNPo1kuyClCfKrGyDtUfzb2y/ZDCAl1/P6vDVqmjfJ4lAq6r87pBZ5hfCvzPV+398qbBUwpGBjwj1KfaPhNnQrLufYbkTKNkvI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
